4-1: 4-1.c
	gcc -std=c99 -o 4-1 4-1.c

4-2: 4-2.c
	gcc -std=c99 -o 4-2 4-2.c -lm

calc: calc.c
	gcc -g -std=c99 -o calc calc.c -lm

4-12: 4-12.c
	gcc -std=c99 -o 4-12 4-12.c

4-13: 4-13.c
	gcc -std=c99 -o 4-13 4-13.c

4-14: 4-14.c
	gcc -std=c99 -o 4-14 4-14.c

clean:
	rm -f *.o *.s 4-1 4-2 calc 4-12 4-13 4-14