5-1: 5-1.c
	gcc -std=c99 -o 5-1 5-1.c

5-2: 5-2.c
	gcc -std=c99 -o 5-2 5-2.c -lm

5-3: 5-3.c
	gcc -std=c99 -o 5-3 5-3.c

5-4: 5-4.c
	gcc -std=c99 -o 5-4 5-4.c

5-5: 5-5.c
	gcc -std=c99 -o 5-5 5-5.c

5-6: 5-6.c
	gcc -std=c99 -o 5-6 5-6.c

5-7: 5-7.c
	gcc -g -std=c99 -o 5-7 5-7.c

5-8: 5-8.c
	gcc -g -std=c99 -o 5-8 5-8.c	

5-9: 5-9.c
	gcc -g -std=c99 -o 5-9 5-9.c	

5-10: 5-10.c
	gcc -g -std=c99 -o 5-10 5-10.c -lm

5-13: 5-13.c
	gcc -g -std=c99 -o 5-13 5-13.c

sort: sort.c
	gcc -g -std=c99 -o mysort sort.c

clean:
	rm -f *.o *.s 5-1 5-2 5-3 5-4 5-5 5-6 5-7 5-8 5-9 5-10 5-13 mysort
